export const curatedData = {
  "massage gun": {
    "title": "Pistolas de Masaje (Massage Guns)",
    "summary": {
      "best_opportunity": "Pistola de Masaje Térmica (Frío/Calor Activo)",
      "best_reason": "La incorporación de terapia térmica activa mediante placa Peltier es una característica premium escasa en Chile. Te permite vender a un precio superior (CLP $59.990) escapando de la guerra de precios y, al cargarse por USB-C, no requiere certificación SEC de enchufe.",
      "safest_product": "Mini Fascia Massage Gun (Carga USB-C)",
      "safest_reason": "Su volumen logístico es mínimo, lo que abarata el flete aéreo. No requiere trámites ante SEC, ISP o Subtel, y tiene una rentabilidad del 69%, ideal para comenzar."
    },
    "products": [
      {
        "id": "thermal_gun",
        "name": "Pistola de Masaje Térmica (Frío/Calor Activo)",
        "thumbnail": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=massage+gun+hot+cold+active+peltier",
        "supplier_verified": true,
        "supplier_years": 8,
        "unit_cost_usd": 14.50,
        "estimated_resale_clp": 59990,
        "estimated_margin_percent": 60,
        "competition_chile": "Low",
        "import_difficulty": "Easy",
        "weight_kg": 0.9,
        "volume_cbm": 0.003,
        "selling_angle": "Doble terapia térmica activa (frío/calor de 10°C a 45°C) para recuperación y desinflamación.",
        "success_reason": "Diferenciación tecnológica real en un mercado de pistolas convencionales saturado. Atrae a deportistas de alto rendimiento.",
        "risks": "Hardware complejo por la placa interna. Requiere inspección previa para descartar fallas de fábrica.",
        "score": 4.8
      },
      {
        "id": "mini_gun",
        "name": "Mini Fascia Massage Gun (Carga USB-C)",
        "thumbnail": "https://images.unsplash.com/photo-1607962837359-5e7e89f866ad?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=mini+massage+gun+pocket+usb-c",
        "supplier_verified": true,
        "supplier_years": 5,
        "unit_cost_usd": 5.20,
        "estimated_resale_clp": 29990,
        "estimated_margin_percent": 69,
        "competition_chile": "Medium",
        "import_difficulty": "Easy",
        "weight_kg": 0.4,
        "volume_cbm": 0.001,
        "selling_angle": "Masajeador ultra portátil de bolsillo, liviano y con carga USB-C universal.",
        "success_reason": "Sin barreras arancelarias ni certificaciones SEC (no usa cargador de pared propio). Excelente para flete aéreo rápido.",
        "risks": "Existen imitaciones plásticas sumamente baratas en Chile. Debes destacar la calidad metálica del chasis en tus publicaciones.",
        "score": 4.4
      },
      {
        "id": "pro_gun",
        "name": "Pistola de Masaje Profesional (Motor Brushless + Maleta EVA)",
        "thumbnail": "https://images.unsplash.com/photo-1591343395902-1adcb454c2e4?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=professional+massage+gun+brushless+eva+case",
        "supplier_verified": true,
        "supplier_years": 6,
        "unit_cost_usd": 17.50,
        "estimated_resale_clp": 49990,
        "estimated_margin_percent": 35,
        "competition_chile": "High",
        "import_difficulty": "Moderate",
        "weight_kg": 1.8,
        "volume_cbm": 0.008,
        "selling_angle": "Dispositivo terapéutico de alta potencia con estuche rígido y 6 cabezales intercambiables.",
        "success_reason": "Demanda estable por kinesiólogos y clínicas. Percepción de valor profesional muy alta.",
        "risks": "Requiere homologación/certificación SEC en aduanas chilenas si se importa con el cargador de pared tradicional de 220V.",
        "score": 3.2
      }
    ]
  },
  "pet grooming accessories": {
    "title": "Accesorios de Aseo de Mascotas (Pet Grooming)",
    "summary": {
      "best_opportunity": "Cepillo Autolimpiante para Mascotas (Slicker Brush)",
      "best_reason": "Es un producto sumamente económico (USD $1.20), ultra liviano y libre de baterías o certificaciones. Su margen supera el 85% y tiene una demanda masiva y constante por dueños de perros y gatos en Chile.",
      "safest_product": "Cepillo Autolimpiante para Mascotas",
      "safest_reason": "Al no tener componentes electrónicos, plásticos complejos ni químicos, pasa la aduana chilena con arancel básico de inmediato (cero riesgo regulatorio)."
    },
    "products": [
      {
        "id": "slicker_brush",
        "name": "Cepillo Autolimpiante Slicker para Perros y Gatos",
        "thumbnail": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=self+cleaning+slicker+brush+dogs+cats",
        "supplier_verified": true,
        "supplier_years": 6,
        "unit_cost_usd": 1.20,
        "estimated_resale_clp": 14990,
        "estimated_margin_percent": 85,
        "competition_chile": "Medium",
        "import_difficulty": "Easy",
        "weight_kg": 0.15,
        "volume_cbm": 0.0005,
        "selling_angle": "Retiro fácil de pelo suelto con solo presionar un botón. Higiene rápida y sin dolor.",
        "success_reason": "Margen comercial brutal. Producto perenne con decisión de compra por impulso y viral en redes sociales.",
        "risks": "Es un producto de bajo precio unitario; necesitas volumen para diluir el costo flete aduanero.",
        "score": 4.9
      },
      {
        "id": "led_clippers",
        "name": "Cortauñas Profesional de Mascotas con Luz LED",
        "thumbnail": "https://images.unsplash.com/photo-1629909615184-74f495363b67?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=pet+nail+clipper+led+light",
        "supplier_verified": true,
        "supplier_years": 4,
        "unit_cost_usd": 2.10,
        "estimated_resale_clp": 19990,
        "estimated_margin_percent": 82,
        "competition_chile": "Low",
        "import_difficulty": "Easy",
        "weight_kg": 0.12,
        "volume_cbm": 0.0003,
        "selling_angle": "Luz LED integrada para visualizar la línea de sangre de la uña, evitando cortes dolorosos.",
        "success_reason": "Resuelve un problema real y de alto temor para los dueños. Baja oferta de modelos con luz en Chile.",
        "risks": "Utiliza pilas de botón. Es importante declarar en la guía aérea que las baterías vienen instaladas y aisladas dentro del equipo.",
        "score": 4.6
      },
      {
        "id": "pet_vacuum",
        "name": "Aspiradora y Limpiador de Pelo Inalámbrico USB",
        "thumbnail": "https://images.unsplash.com/photo-1563422156298-c778a278f9a5?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=pet+hair+vacuum+cleaner+rechargeable",
        "supplier_verified": true,
        "supplier_years": 3,
        "unit_cost_usd": 6.80,
        "estimated_resale_clp": 24990,
        "estimated_margin_percent": 55,
        "competition_chile": "High",
        "import_difficulty": "Easy",
        "weight_kg": 0.8,
        "volume_cbm": 0.004,
        "selling_angle": "Succión silenciosa para aspirar el pelo suelto directamente de la mascota sin asustarla.",
        "success_reason": "Propuesta atractiva y altamente visual para publicidad en TikTok e Instagram Ads.",
        "risks": "Saturación media en marketplaces tradicionales. Los motores de gama baja pueden tener poca potencia de succión.",
        "score": 3.8
      }
    ]
  },
  "kitchen tools": {
    "title": "Utensilios y Herramientas de Cocina (Kitchen Tools)",
    "summary": {
      "best_opportunity": "Picadora de Ajo Eléctrica USB (Mini Chopper)",
      "best_reason": "Tiene una demanda altísima por su utilidad diaria en el hogar. Al cargarse por USB, evita regulaciones eléctricas (SEC), y su bajo costo y peso hacen viable importarlo en lotes de cientos de unidades vía flete consolidado.",
      "safest_product": "Picadora de Ajo Eléctrica USB",
      "safest_reason": "Se interna como un electrodoméstico menor USB de bajo voltaje, sin complicaciones arancelarias especiales ni inspecciones complejas de salubridad."
    },
    "products": [
      {
        "id": "garlic_chopper",
        "name": "Picadora de Ajo y Verduras Eléctrica USB",
        "thumbnail": "https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=electric+mini+garlic+chopper+wireless+usb",
        "supplier_verified": true,
        "supplier_years": 7,
        "unit_cost_usd": 3.20,
        "estimated_resale_clp": 18990,
        "estimated_margin_percent": 72,
        "competition_chile": "Medium",
        "import_difficulty": "Easy",
        "weight_kg": 0.3,
        "volume_cbm": 0.0008,
        "selling_angle": "Procesador inalámbrico express. Pica ajo, jengibre y chiles en 10 segundos con un botón.",
        "success_reason": "Ahorra tiempo en la cocina, es recargable y de fácil lavado. Atrae al público hogareño y gastronómico.",
        "risks": "Contacto con alimentos. Las aduanas chilenas pueden exigir declaración de plástico libre de BPA (BPA-free) del fabricante.",
        "score": 4.5
      },
      {
        "id": "water_dispenser",
        "name": "Dispensador Automático de Agua USB para Bidón",
        "thumbnail": "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=automatic+water+dispenser+pump+usb+barrel",
        "supplier_verified": true,
        "supplier_years": 10,
        "unit_cost_usd": 1.90,
        "estimated_resale_clp": 12990,
        "estimated_margin_percent": 75,
        "competition_chile": "High",
        "import_difficulty": "Easy",
        "weight_kg": 0.25,
        "volume_cbm": 0.0006,
        "selling_angle": "Bomba extractora eléctrica recargable para botellones de agua estándar de 20 litros.",
        "success_reason": "Producto masivo de altísima rotación. Utilizado tanto en hogares como en oficinas chilenas.",
        "risks": "Altísima saturación. Competencia extrema de precios en Santiago. Requiere márgenes delgados u ofertas por pack de unidades.",
        "score": 4.1
      },
      {
        "id": "knife_sharpener",
        "name": "Afilador Eléctrico de Cuchillos de 3 Etapas (220V)",
        "thumbnail": "https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=professional+electric+knife+sharpener+3+stage",
        "supplier_verified": true,
        "supplier_years": 5,
        "unit_cost_usd": 8.50,
        "estimated_resale_clp": 34990,
        "estimated_margin_percent": 58,
        "competition_chile": "Low",
        "import_difficulty": "Moderate",
        "weight_kg": 1.2,
        "volume_cbm": 0.0025,
        "selling_angle": "Afilado profesional en segundos con guías angulares y muelas de diamante sintético.",
        "success_reason": "Pocos competidores de calidad en Chile. El afilado de cuchillos es una necesidad transversal.",
        "risks": "Al conectarse directamente a la red eléctrica (220V), **requiere certificación obligatoria de la SEC** (trámite QR eléctrico en Chile).",
        "score": 4.2
      }
    ]
  },
  "car accessories": {
    "title": "Accesorios para Autos (Car Accessories)",
    "summary": {
      "best_opportunity": "Compresor de Aire Portátil Digital USB",
      "best_reason": "Ofrece una gran utilidad para emergencias y un valor percibido muy superior a su costo real. Al ser recargable USB-C, no presenta complejidades de internación y su tamaño compacto optimiza los costos de envío.",
      "safest_product": "Compresor de Aire Portátil Digital USB",
      "safest_reason": "Es un artículo de electrónica portátil USB básico con excelente tasa de aceptación en aduana y nulas exigencias de homologación en Chile."
    },
    "products": [
      {
        "id": "car_compressor",
        "name": "Compresor de Aire Inteligente Portátil USB",
        "thumbnail": "https://images.unsplash.com/photo-1617469167446-80e3a4466551?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=portable+smart+car+air+compressor+digital+tire+inflator",
        "supplier_verified": true,
        "supplier_years": 6,
        "unit_cost_usd": 7.80,
        "estimated_resale_clp": 32990,
        "estimated_margin_percent": 67,
        "competition_chile": "Medium",
        "import_difficulty": "Easy",
        "weight_kg": 0.55,
        "volume_cbm": 0.0012,
        "selling_angle": "Mini inflador inteligente de neumáticos con corte automático digital al llegar a la presión fijada.",
        "success_reason": "Valor percibido alto. Excelente para ciclistas, motociclistas y automovilistas. Compra por prevención/seguridad.",
        "risks": "La batería de litio integrada de alta capacidad puede restringir envíos por vía aérea express rápido. Se recomienda vía marítima consolidada.",
        "score": 4.7
      },
      {
        "id": "car_vacuum",
        "name": "Aspiradora de Auto Inalámbrica Potente USB",
        "thumbnail": "https://images.unsplash.com/photo-1507136566006-cfc505b114fc?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=high+power+cordless+car+vacuum+cleaner+rechargeable",
        "supplier_verified": true,
        "supplier_years": 4,
        "unit_cost_usd": 5.50,
        "estimated_resale_clp": 24990,
        "estimated_margin_percent": 63,
        "competition_chile": "High",
        "import_difficulty": "Easy",
        "weight_kg": 0.65,
        "volume_cbm": 0.002,
        "selling_angle": "Aspiradora compacta de alta potencia de succión con boquillas para rincones del automóvil.",
        "success_reason": "Ideal para la limpieza rápida del vehículo. Muy atractiva para campañas de marketing en video.",
        "risks": "Mercado altamente competitivo con márgenes ajustados si no se diferencia el producto mediante un motor brushless de alta succión.",
        "score": 4.0
      },
      {
        "id": "fm_transmitter",
        "name": "Transmisor Bluetooth FM para Auto QC 3.0",
        "thumbnail": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=car+bluetooth+fm+transmitter+qc3.0",
        "supplier_verified": true,
        "supplier_years": 9,
        "unit_cost_usd": 1.80,
        "estimated_resale_clp": 9990,
        "estimated_margin_percent": 71,
        "competition_chile": "High",
        "import_difficulty": "Moderate",
        "weight_kg": 0.08,
        "volume_cbm": 0.0002,
        "selling_angle": "Conecta tu smartphone a radios antiguas mediante Bluetooth y carga rápida QC3.0 integrada.",
        "success_reason": "Costo de compra bajísimo, cabe en cualquier caja. Muy fácil de despachar masivamente en Chile.",
        "risks": "Al ser un transmisor de radiofrecuencia (FM/Bluetooth), aduanas chilenas (Subtel) podría retenerlo para verificación, aunque para importaciones menores suele pasar sin problemas.",
        "score": 3.9
      }
    ]
  },
  "smart home gadgets": {
    "title": "Dispositivos para el Hogar Inteligente (Smart Home)",
    "summary": {
      "best_opportunity": "Paneles LED Hexagonales RGB Inteligentes",
      "best_reason": "Son paneles de iluminación modular muy llamativos que se venden por impulso en el nicho gamer y decorativo. Al alimentarse por USB, evitan certificaciones eléctricas SEC, y su peso ligero mantiene el flete bajo.",
      "safest_product": "Paneles LED Hexagonales RGB Inteligentes",
      "safest_reason": "Alimentación USB-5V, producto decorativo no invasivo que pasa aduanas sin trabas de sanidad, electricidad o seguridad."
    },
    "products": [
      {
        "id": "hexagon_panels",
        "name": "Paneles LED Hexagonales RGB Inteligentes (USB)",
        "thumbnail": "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=modular+hexagon+led+lights+rgb+smart+usb",
        "supplier_verified": true,
        "supplier_years": 5,
        "unit_cost_usd": 9.50,
        "estimated_resale_clp": 39990,
        "estimated_margin_percent": 66,
        "competition_chile": "Low",
        "import_difficulty": "Easy",
        "weight_kg": 0.7,
        "volume_cbm": 0.0025,
        "selling_angle": "Iluminación modular interactiva con control por app y sincronización rítmica con música.",
        "success_reason": "Fuerte tracción en redes sociales y setup gamer. Pocos competidores formales en tiendas físicas en Chile.",
        "risks": "La calidad de las uniones plásticas y el conector USB de interconexión puede ser deficiente en los proveedores más económicos.",
        "score": 4.6
      },
      {
        "id": "smart_plug",
        "name": "Enchufe Inteligente Wi-Fi Smart Plug (Norma Chilena)",
        "thumbnail": "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=tuya+smart+wifi+plug+chile+italian+standard+220v",
        "supplier_verified": true,
        "supplier_years": 8,
        "unit_cost_usd": 2.20,
        "estimated_resale_clp": 14990,
        "estimated_margin_percent": 70,
        "competition_chile": "High",
        "import_difficulty": "Difficult",
        "weight_kg": 0.12,
        "volume_cbm": 0.0004,
        "selling_angle": "Enchufe inteligente compatible con Alexa y Google Home para automatizar cualquier artefacto.",
        "success_reason": "Alta demanda por automatización del hogar. Su costo unitario permite un margen enorme si se comercializa masivamente.",
        "risks": "**CRÍTICO:** Los enchufes eléctricos de 220V requieren **certificación SEC obligatoria** en Chile. Venderlos sin certificación arriesga multas altísimas y decomiso en aduana.",
        "score": 3.0
      },
      {
        "id": "smart_camera",
        "name": "Cámara de Seguridad Robotizada Inteligente Wi-Fi",
        "thumbnail": "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&auto=format&fit=crop",
        "alibaba_link": "https://www.alibaba.com/trade/search?SearchText=smart+wifi+ip+security+camera+robot+pan+tilt",
        "supplier_verified": true,
        "supplier_years": 7,
        "unit_cost_usd": 8.90,
        "estimated_resale_clp": 29990,
        "estimated_margin_percent": 56,
        "competition_chile": "High",
        "import_difficulty": "Easy",
        "weight_kg": 0.45,
        "volume_cbm": 0.0015,
        "selling_angle": "Cámara IP de vigilancia 1080P con visión nocturna, seguimiento automático de movimiento y audio bidireccional.",
        "success_reason": "Alta preocupación por la seguridad del hogar en Chile. Producto de venta continua y fácil configuración.",
        "risks": "Gran cantidad de vendedores informales. Requiere que la aplicación sea intuitiva y esté traducida correctamente al español (Tuya/SmartLife).",
        "score": 3.8
      }
    ]
  }
};
